services:
  dump-api:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    container_name: dump_api
    ports:
      - "5207:10000"
    env_file:
      - ./backend/.env
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:10000
    restart: unless-stopped